name: Salesforce Deploy

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # - name: Install SF CLI
    #   uses: svierk/sfdx-cli-setup@main
        
    # - name: Salesforce Auth
    #   uses: svierk/sfdx-login@main
    #   with:
    #       client-id: 3MVG9rZjd7MXFdLiB9e1dStjFXbnQSC039gnxY5W10JLwX3HHwkztpdCV6nKMygpxA1u_UacE9SsULXA4Zjqp
    #       jwt-secret-key: ${{ secrets.SFDX_JWT_SECRET_KEY }}
    #       username: vkdwivedi.20@personal.dev


    - name: Remove conflicting CLI (sfdx)
      run: |
          sudo rm -f /usr/local/bin/sfdx
          sudo rm -rf ~/.local/lib/node_modules/sfdx-cli

    - name: Install Salesforce CLI (sf)
      run: npm install @salesforce/cli --global



    # - name: Decrypt Server Key (if encrypted)
    #   run: openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K ${{ secrets.SERVER_KEY_DECRYPTION_KEY }} -iv ${{ secrets.SERVER_KEY_IV }}
    #   # Adjust path and secret names based on your setup

    - name: Authenticate to Salesforce
      run: |
          sf org login jwt \
          --clientid 3MVG9rZjd7MXFdLiB9e1dStjFXbnQSC039gnxY5W10JLwX3HHwkztpdCV6nKMygpxA1u_UacE9SsULXA4Zjqp \
          --jwtkeyfile force-app/certs/server.key \
          --username vkdwivedi.20@personal.dev \
          --alias targetOrg



    #  run: sf org login jwt --client-id 3MVG9rZjd7MXFdLiB9e1dStjFXbnQSC039gnxY5W10JLwX3HHwkztpdCV6nKMygpxA1u_UacE9SsULXA4Zjqp --jwt-key-file ${{ secrets.SFDX_JWT_SECRET_KEY }} --username vkdwivedi.20@personal.dev --alias targetOrg
    
    - name: Deploy Salesforce Metadata   
      run: sf deploy metadata --source-dir force-app/main/default --target-org targetOrg


